# Site settings
title: Ruby developer's blog
email: max@philippov.net
description: > # this means to ignore newlines until "baseurl:"
  Blog about practical Ruby on Rails development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.philippov.net" # the base hostname & protocol for your site
github_username:  maksimf

# Build settings
markdown: kramdown
